documents/urls.py
from django.urls import path, include
from django.conf.urls import url
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'documents'

router = routers.DefaultRouter()
router.register(r'ips', views.IpList)

urlpatterns = [
    path('', include(router.urls)),

    # fomrs for adding objects #
    path('add/university/', views.UniversityCreateView.as_view(), name='university_add'),
    path('add/faculty/', views.FacultyCreateView.as_view(), name='faculty_add'),
    path('add/course/', views.CourseCreateView.as_view(), name='course_add'),
    path('add/file/', views.FileCreateView.as_view(), name='file_add'),
    # end of forms #


    # start of ajax calls #
    path('<int:pk>/', views.CourseUpdateView.as_view(), name='course_change'),
    path('ajax/load-faculties/', views.load_faculties, name='ajax_load_faculties'),  # <-- this one here
    path('ajax/load-universities/', views.load_universities, name='ajax_load_universities'),  # <-- this one here
    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),  # <-- this one here
    # end of ajax calls #

    # start of like #
    path('file/<int:pk>/like', views.FileLikeRedirect.as_view(), name="like"),
    path('api/file/<int:pk>/like', views.FileLikeApi.as_view(), name="like-api"),
    # end of likes #

    # start of objects views #
    path('course/<int:pk>/', views.CourseSingleView.as_view(), name="course-detail"),
    path('file/<int:pk>/', views.file_detail, name="file-detail"),
    path('university/<int:pk>/', views.UniversitySingleView.as_view(), name="university-detail"),
    path('universities/', views.UniversityListView.as_view(), name="universities"),
    path('university/<int:pk_alt>/faculty/<int:pk>/', views.FacultySingleView.as_view(), name="faculty-detail"),
    # end of objects views #
    path('check/', views.CheckIp.as_view()),

    # url(r'api/list', views.get_file_list, name='get_file_list'),
]
# ,views.CourseSingleView.as_view()
urlpatterns += format_suffix_patterns([
    # API to map the student record
    url(r'^api/list/$',
        views.FileRecordView.as_view(),
        name='files_list'),
])

wara8z/urls.py
from django.conf import settings
from django.conf.urls.static import static
from documents.views import home

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('social-auth/',
         include('social_django.urls', namespace='social')),

    path('', home, name="home"),
    # path('', include(('documents.urls','documents'), namespace='documents')),

    # path('', include(('documents.urls', 'documents'))),
    path('', include('documents.urls')),

]

documents/models.py
# Create your models here.
from django.db import models
from PyPDF2 import PdfFileReader
from django.core.files.storage import default_storage as storage
import boto3
from decouple import config
from django.conf import settings
from django.urls import reverse

BUCKET_NAME = config('BUCKET_NAME', cast=str)  # replace with your bucket name
ACCESS_ID = config('ACCESS_ID')
ACCESS_KEY = config('ACCESS_KEY')



class Ip(models.Model):
    address=models.CharField(max_length=20)

    def __str__(self):
        return self.address


class University(models.Model):
    name = models.CharField(max_length=50)


    def __str__(self):
        return self.name


class Faculty(models.Model):
    name = models.CharField(max_length=50)
    university = models.ForeignKey(
        'University',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=50)
    university = models.ForeignKey(
        'University',
        on_delete=models.CASCADE
    )
    faculty = models.ForeignKey(
        'Faculty',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class File(models.Model):
    img_list = []

    categories_choices = [("أسئلة سنوات", "أسئلة سنوات"), ("ملخصات", 'ملخصات')]
    # university = models.OneToOneField(University, on_delete=models.CASCADE)
    university = models.ForeignKey(
        'University',
        on_delete=models.CASCADE
    )
    faculty = models.ForeignKey(
        'Faculty',
        on_delete=models.CASCADE
    )
    course = models.ForeignKey(
        'Course',
        on_delete=models.CASCADE,
    )
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='file_likes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return "/file/%i/" % self.id

    def get_like_url(self):
        return reverse("documents:like", kwargs={"pk": self.pk})

    def get_api_like_url(self):
        return reverse("documents:like-api", kwargs={"pk": self.pk})

    created_at_date = models.DateTimeField(auto_now_add=True)

    category = models.CharField(max_length=20, choices=categories_choices)
    pdf = models.FileField()
    thumbnail = models.CharField(max_length=1000)
    images_number = models.PositiveIntegerField(default=1)

    def get_numofpages(self):
        ff = storage.open(self.pdf.name, 'rb')
        file = PdfFileReader(ff)
        number_of_pages = file.getNumPages()
        ff.close()

        return number_of_pages

    def text_extractor(self):
        text = ""
        ff = storage.open(self.pdf.name, 'rb')
        file = PdfFileReader(ff)
        # get the first page
        for x in range(0, self.get_numofpages()):
            page = file.getPage(x)
            text = text + "page:" + str(x + 1) + '\n' + page.extractText()
        ff.close()

        return text

    def imgs(self):

        directory = "media/" + self.university.name + "/" + self.faculty.name + "/" + self.course.name + "/" + self.pdf.name
        imgs = []
        s3 = boto3.resource('s3',
                            aws_access_key_id=ACCESS_ID,
                            aws_secret_access_key=ACCESS_KEY)
        my_bucket = s3.Bucket(BUCKET_NAME)
        for object in my_bucket.objects.filter(Prefix=directory):
            imgs.append('https://wara8-static.s3.amazonaws.com' + '/' + object.key)

        return imgs

    def size_cal(self):
        return str(self.pdf.size / 1024 / 1024)[0:3]


class Comment(models.Model):
    file = models.ForeignKey(File,
                             on_delete=models.CASCADE,
                             related_name='comments')

    body = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.user, self.file.pdf)

documents/views.py
from django.views.generic import ListView, CreateView, UpdateView, DetailView, RedirectView
from django.shortcuts import render, get_object_or_404
from .serializers import FileSerializer, UniversitySerializer,IpSerializer

from django.urls import reverse_lazy
from .models import Course, Faculty, File, University, Comment,Ip
from .forms import CourseForm, FileForm, FacultyForm, CommentForm,UniversityForm
from hitcount.views import HitCountDetailView

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, generics, viewsets

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.contrib.auth.models import User





class CheckIp(generics.ListAPIView):
    serializer_class = IpSerializer

    def get_queryset(self):
        """
        Optionally restricts the returned purchases to a given user,
        by filtering against a `username` query parameter in the URL.
        """
        queryset = Ip.objects.all()
        address = self.request.query_params.get('address', None)
        print(address)
        if address is not None:
            queryset = queryset.filter(address=address)
        return queryset


class IpList(viewsets.ModelViewSet):
    queryset = Ip.objects.all()
    serializer_class = IpSerializer




class FileRecordView(APIView):
    """
    A class based view for creating and fetching student records
    """

    def get(self, format=None):
        """
        Get all the student records
        :param format: Format of the student records to return to
        :return: Returns a list of student records
        """
        files = File.objects.all()
        serializer = FileSerializer(files, many=True)
        return Response(serializer.data)

    def post(self, request):
        """
        Create a student record
        :param format: Format of the student records to return to
        :param request: Request object for creating student
        :return: Returns a student record
        """
        serializer = UniversitySerializer(data=request.data)
        if serializer.is_valid(raise_exception=ValueError):
            serializer.create(validated_data=request.data)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.error_messages,
                        status=status.HTTP_400_BAD_REQUEST)


def home(request):
    universities = University.objects.all()
    faculties = Faculty.objects.all()
    courses = Course.objects.all()
    files = File.objects.all()
    return render(request, 'home.html',
                  {'university_list': universities, 'faculty_list': faculties, "course_list": courses,
                   "file_list": files})


def footerLinks(request):
    universities = University.objects.all()
    return render(request, 'base.html',
                  {'university_list': universities})


class CourseListView(ListView):
    model = Course
    context_object_name = 'courses'


class UniversitySingleView(DetailView):
    model = University
    template_name = 'documents/single_university.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UniversitySingleView, self).get_context_data(**kwargs)
        # Add extra context from another model
        context['faculties'] = Faculty.objects.filter(university_id=self.kwargs['pk'])
        return context


class FacultySingleView(DetailView):
    model = Faculty
    template_name = 'documents/single_faculty.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(FacultySingleView, self).get_context_data(**kwargs)
        # Add extra context from another model
        context['courses'] = Course.objects.filter(faculty_id=self.kwargs['pk'])
        page_alt = University.objects.get(id=self.kwargs.get('pk_alt', ''))
        context['page_alt'] = page_alt

        return context


class CourseSingleView(DetailView):
    model = Course
    template_name = 'documents/single_course.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CourseSingleView, self).get_context_data(**kwargs)
        # Add extra context from another model
        context['files'] = File.objects.filter(course_id=self.kwargs['pk'])
        return context


# class FileSingleView(HitCountDetailView):
#     model = File
#     template_name = 'documents/single_file.html'
#     count_hit = True  # set to True if you want it to try and count the hit


def file_detail(request, pk):
    file = get_object_or_404(File, pk=pk)
    # List of active comments for this post
    comments = file.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.file = file
            new_comment.user=request.user
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request,
                  'documents/single_file.html',
                  {'file': file,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form})


class FileLikeApi(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, pk, format=None):
        pk = self.kwargs.get("pk")
        obj = get_object_or_404(File, pk=pk)
        url_ = obj.get_absolute_url()
        user_ = self.request.user
        updated = False
        liked = False
        counts = obj.likes.count()

        # print(user_)
        if user_.is_authenticated:
            if user_ in obj.likes.all():
                liked = False
                obj.likes.remove(user_)
            else:
                liked = True
                obj.likes.add(user_)
                updated = True

        data = {
            "updated": updated,
            "liked": liked,
            "likescount": counts
        }
        return Response(data)


class FileLikeRedirect(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        pk = self.kwargs.get("pk")
        print(pk)
        obj = get_object_or_404(File, pk=pk)
        url_ = obj.get_absolute_url()
        user_ = self.request.user
        # print(user_)
        if user_.is_authenticated:
            if user_ in obj.likes.all():
                obj.likes.remove(user_)
            else:
                obj.likes.add(user_)
        return url_


class UniversityListView(ListView):
    model = University
    template_name = 'documents/universities.html'
    context_object_name = 'universities'


class UniversityCreateView(CreateView):
    model = University
    success_url = reverse_lazy('home')
    form_class = UniversityForm


class FileCreateView(CreateView):
    model = File
    # fields = ('name', 'universigty', 'country', 'city')
    success_url = reverse_lazy('home')
    form_class = FileForm


class FacultyCreateView(CreateView):
    model = Faculty
    success_url = reverse_lazy('universities')
    form_class = FacultyForm


class CourseCreateView(CreateView):
    model = Course
    # fields = ('name', 'university', 'faculty')
    success_url = reverse_lazy('home')
    form_class = CourseForm


class CourseUpdateView(UpdateView):
    model = Course
    # fields = ('name', 'university', 'faculty')
    success_url = reverse_lazy('home')
    form_class = CourseForm


def load_faculties(request):
    university_id = request.GET.get('university')
    faculties = Faculty.objects.filter(university_id=university_id).order_by('name')
    return render(request, 'documents/faculty_dropdown_list_options.html', {'faculties': faculties})


def load_universities(request):
    course_id = request.GET.get('course')
    universities = University.objects.filter(course_id=course_id).order_by('name')
    return render(request, 'documents/university_dropdown_list_options.html', {'universities': universities})


def load_courses(request):
    faculty_id = request.GET.get('faculty')
    courses = Course.objects.filter(faculty_id=faculty_id).order_by('name')
    return render(request, 'documents/course_dropdown_list_options.html', {'courses': courses})

templates/documents/course_add.html
{% block content %}
  <h2>Course Form</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'course_changelist' %}">Nevermind</a>
  </form>
{% endblock %}

templates/documents/course_change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/documents/course_changelist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/documents/course_dropdown_list_options.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

templates/documents/course_form.html
{#{% block content %}#}
{#  <h2>Course Form</h2>#}
{#  <form method="post" novalidate>#}
{#    {% csrf_token %}#}
{#    <table>#}
{#      {{ form.as_table }}#}
{#    </table>#}
{#    <button type="submit">Save</button>#}
{#    <a href="{% url 'course_changelist' %}">Nevermind</a>#}
{#  </form>#}
{#{% endblock %}#}

{#{% extends 'base.html' %}#}

{% block content %}

  <h2>Course Form</h2>

  <form method="post" id="courseForm" data-faculties-url="{% url 'documents:ajax_load_faculties' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_university").change(function () {
      var url = $("#courseForm").attr("data-faculties-url");  // get the url of the `load_cities` view
      var universityId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'university': universityId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_faculty").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

templates/documents/faculty_dropdown_list_options.html
<option value="">---------</option>
{% for faculty in faculties %}
<option value="{{ faculty.pk }}">{{ faculty.name }}</option>
{% endfor %}

templates/documents/faculty_form.html
{% extends 'base.html' %}
{% block content %}
 <h2>Faculty Form</h2>

  <form method="post" id="facultyForm">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
{#    <a href="{% url 'course_changelist' %}">Nevermind</a>#}
  </form>
{% endblock content %}

templates/documents/single_file.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
    <!-- Page Title
		============================================= -->
    <section id="page-title">

        <div id="top" class="container clearfix">
            <div class="col_full">
                <ol class="breadcrumb ">
                    <li class="breadcrumb-item h5"><a
                            href="{% url 'documents:university-detail' file.university.pk %}">{{ file.university }}</a>
                    </li>
                    <li class="breadcrumb-item h5"><a
                            href="{% url 'documents:faculty-detail' file.university.pk file.faculty.pk %}">{{ file.faculty }}</a>
                    </li>

                    <li class="breadcrumb-item active h5" aria-current="page">{{ file.course }}</li>
                </ol>
            </div>

            <div class="col_one_fourth"><a href="#">
                                <img alt="100%x180" src="{{ file.imgs.pop }}" class="img-thumbnail "
                style="height: 350px; width: 100%; display: block;">
            </a></div>
            <div class="col_three_fourth col_last">
                <h2 class="h2">{{ file.pdf.name }}</h2>

                <p>Likes: <a class="like-btn" data-href="{{ file.get_api_like_url }}"
                             data-likes="{{ file.likes.count }}"
                             href='{{ file.get_like_url }}'>{{ file.likes.count }}
                    {% if user in file.likes.all %}
                        Unlike
                    {% else %}
                        Like
                    {% endif %}
                </a></p>


                <p class="h5">{{ file.faculty }}->{{ file.course }}</p>
                <p class="h5">{{ file.created_at_date.day }}-{{ file.created_at_date.month }}-{{ file.created_at_date.year }}</p>

                <hr>
                {#                <p class="h5">{{ file.size_cal }}MB#}
                {#                    | <i class="green fas fa-copy"> صفحات {{ file.images_number }}  </i> #}
                {#                    | <i#}
                {#                            class="green fas fa-eye">{{ hitcount.total_hits }}</i></p>#}


            </div>

        </div>

    </section><!-- #page-title end -->

    <!-- Content
    ============================================= -->


    <section id="content">

        <div class="content-wrap">

            <div class="container clearfix">

                <div class="col_full ">
                    {#                    <embed src="https://drive.google.com/viewerng/#}
                    {#viewer?embedded=true&url={{ file.pdf.url }}" width="500" height="375">#}
                    {##}
                    {#                    <file data="{{ file.pdf.url }}" type="application/pdf">#}
                    {#                        <embed src="{{ file.pdf.url }}" type="application/pdf"/>#}
                    {#                    </file>#}


                    {#<div  data-big="1" data-lightbox="gallery" style="margin-right: -1px; position: relative; height: 513.75px;">#}
                    {% for img in file.imgs %}
                        <img data-src="{{ img }}" class="page img-fluid lazyload "
                             alt="{{ file.pdf.name }}" align="center" style=" width: 100%;">

                        {#                                            <a href="{{ img }}" data-lightbox="gallery-item"#}
                        {#                                               style="width: 228px; position: absolute; left: 912px; top: 0px;"><img class="page image_fade lazyload"#}
                        {#                                                                                                                     data-src="{{ img }}"#}
                        {#                                                                                                                     alt="{{ file.pdf.name }}"#}
                        {#                                                                                                                     style="opacity: 1;"></a>#}
                    {% endfor %}
                    {#                        <iframe src="https://docs.google.com/gview?url={{ file.pdf.url }}&embedded=true"#}
                    {#                                style="width:100%; height:1000px;" frameborder="0"></iframe>#}
                    {#                        <script>#}
                    {#                            $(document).load(function () {#}
                    {#                                $(".ndfHFb-c4YZDc-Bz112c.ndfHFb-c4YZDc-DH6Rkf-Bz112c").css('display', 'none');#}
                    {#                            });#}
                    {##}
                    {##}
                    {#                        </script>#}


                </div>
                <hr>
                <p id="end" class="h5 text-center"></p>

                <a class="txt" href="#" id="loadMore">تحميل المزيد</a>

                <p class="totop ">
                    <a class="txt" href="#top">Back to top</a>
                </p>


            </div>


        </div>

        </div>

    </section><!-- #content end -->

    {#    <p>{{ file.text_extractor }}</p>#}

    {% if user.is_authenticated %}

        {% with comments.count as total_comments %}
            <h2>
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h2>
        {% endwith %}
        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    تعليق {{ forloop.counter }} بواسطة {{ comment.user }}
                    {{ comment.created }}<img style="width:36px;height: 36px;"
                                              class="img-responsive img-circle "
                                              src="{{ comment.user.profile.photo.url }}"/>
                </p>

                {{ comment.body|linebreaks }}
            </div>
        {% empty %}
            <p>There are no comments yet.</p>
        {% endfor %}
        {% if new_comment %}
            <h2>Your comment has been added.</h2>
        {% else %}
            <h2>Add a new comment</h2>
            <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
            </form>
        {% endif %}
    {% else %}
        <p>يجب عليك <a href="{% url "login" %}">تسجيل الدخول</a> قبل ترك اي تعليق على هذا الملف</p>
    {% endif %}
    <hr>

    <style>

        #end {
            font-family: "Cairo";
            color: #c0392b;
        }

        .green {
            color: #6cb76a;
        }

        img.page {
            display: none;
            padding: 10px;
            border-width: 0 1px 1px 0;
            border-style: solid;
            border-color: #fff;
            box-shadow: 0 1px 1px #ccc;
            margin-bottom: 15px;
            background-color: #f1f1f1;

        }

        .totop {
            position: fixed;
            bottom: 10px;
            right: 20px;
        }

        .totop a {
            display: none;
        }

        a.txt, a.txt:visited {
            color: #33739E;
            text-decoration: none;
            display: block;
            margin: 10px 0;
        }

        a:hover {
            text-decoration: none;
        }

        #loadMore {
            padding: 10px;
            font-size: 20px;
            text-align: center;
            background-color: lightseagreen;
            font-family: "Cairo Light";
            color: #fff;
            border-width: 0 1px 1px 0;
            border-style: solid;
            border-color: #fff;
            box-shadow: 0 1px 1px #ccc;
            transition: all 600ms ease-in-out;
            -webkit-transition: all 600ms ease-in-out;
            -moz-transition: all 600ms ease-in-out;
            -o-transition: all 600ms ease-in-out;
        }

        #loadMore:hover {
            background-color: #fff;
            color: #33739E;
        }
    </style>




    <script>


        window.addEventListener("load", function (event) {
            /* This is just to add random string after each url. Do not copy. */
            /* Yes, you... Do not copy. */
            let images = document.querySelectorAll("img.page");
            images.forEach(image => {
                let src = image.getAttribute("data-src");
                image.setAttribute("data-src", src + "?" + Math.random());
            });
            lazyload(images);

        });


        $(document).ready(function () {

            if ($("img.page").length <= 4) {
                $("#loadMore").hide();
            }
        });

        $(function () {
            $("img.page").slice(0, 4).show();
            $("#loadMore").on('click', function (e) {

                e.preventDefault();
                $("img.page:hidden").slice(0, 4).slideDown();

                if ($("img.page:hidden").length == 0) {
                    $("#loadMore").fadeOut('slow');
                    $("#end").text("نهاية الملف")
                }
                //$('html,body').animate({
                //  scrollTop: $(this).offset().top
                //}, 5000);
            });
        });

        $('a[href=#top]').click(function () {
            $('body,html').animate({
                scrollTop: 0
            }, 600);
            return false;
        });

        $(window).scroll(function () {
            if ($(this).scrollTop() > 50) {
                $('.totop a').fadeIn();
            } else {
                $('.totop a').fadeOut();
            }
        });

    </script>
{% endblock content %}

templates/documents/university_dropdown_list_options.html
<option value="">---------</option>
{% for university in universities %}
<option value="{{ university.pk }}">{{ university.name }}</option>
{% endfor %}

templates/documents/university_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container" style="margin-top:50px;margin-bottom: 50px;">
        {#        <div class="row">#}

        <h2>إضافة جامعة</h2>
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        {#        </div>#}
    </div>

{% endblock %}